AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Facial-App layer about functions and API GATEWAY

Parameters:
  Stage:
    Type: String

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ../functions/hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Timeout: 60
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get

