AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Facial-App Architecture from CloudFormation'

Parameters:
  Stage:
    Type: String

Resources:
  StackNetworking:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
          Stage: !Ref Stage
      Tags:
        - Key: ProyID
          Value: FACIAL-ID
      TemplateURL: cloud-architecture/networking.yaml
  StackBuckets:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
          Stage: !Ref Stage
      Tags:
        - Key: ProyID
          Value: FACIAL-ID
      TemplateURL: cloud-architecture/buckets.yaml
  StackApis:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
          Stage: !Ref Stage
      Tags:
        - Key: ProyID
          Value: FACIAL-ID
      TemplateURL: cloud-architecture/functions.yaml